DEFAULT_APP_VARIABLE_PREFIX = "CHALLENGE_"

DEFAULT_REDIS_EXPIRE = 10
DEFAULT_REDIS_HOST = "localhost"
DEFAULT_REDIS_PORT = 6379

DEFAULT_BACKEND_HOST = "localhost"
DEFAULT_BACKEND_PORT = 5000

GHIBLI_FILMS_URL = "https://ghibliapi.herokuapp.com/films"
GHIBLI_PEOPLE_URL = "https://ghibliapi.herokuapp.com/people"
