version: '3.3'
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - "${CHALLENGE_REDIS_PORT}"
  backend:
    restart: always
    env_file:
      - ./.env
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "${CHALLENGE_BACKEND_PORT}:${CHALLENGE_BACKEND_PORT}"
    command: bash -c "python ./run.py"
