version: '3.3'
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  backend:
    restart: always
    env_file:
      - ./.env
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    command: bash -c "python ./run.py"
